title: Jacob Sanford . com
description: Plunging From the Shoulders of Giants
author: Jacob Sanford
github: https://github.com/JacobSanford
about: Enthusiastic solutions architect at @unb-libraries, Ops/DevOps aficionado, Drupal evangelist.
disqus_shortname: jacobsanford
google_analytics: UA-21448090-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/JacobSanford"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jacob-sanford-5762bb63"
    - icon: fa-stack-exchange
      link: "#"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://jacobsanford.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
